### ISSUE TITLE
typescript-to-json-schema failing

### ISSUE THREAD

**Issue by sameerveda** [ritz078/transform#276] opened 2021-03-14 14:39 UTC
![image](https://user-images.githubusercontent.com/22796631/111072610-4e4c0b00-8501-11eb-9cff-9d8d1f50cdbc.png)

**Comment by DanielRHayes** [comment] 2021-03-20 15:07
Duplicate of https://github.com/ritz078/transform/issues/259

**Comment by ritz078** [comment] 2021-06-26 19:45
closing in favor of #259

**Closed by ritz078** 2021-06-26 19:45 UTC
