### ISSUE TITLE
CSS to Tailwind - Issue with special character like %

### ISSUE THREAD

**Issue by Triloworld** [ritz078/transform#388] opened 2024-01-18 14:56 UTC
Used to reproduction: https://transform.tools/css-to-tailwind

Information:
> (postcss) CssSyntaxError Unknown word (1:1) > 1 | Unable to convert CSS | ^

```css
@-webkit-keyframes empty {
    0% {
        opacity: 1;
    }
}
```

Propose:
Add option to:
- ignore and remove from output
- stay in output in original as-is
- block compile (default option)

There will be always some new operators that can be added independently from this package

**Comment by ritz078** [comment] 2024-02-17 10:12
The issue is open in the upstream project https://github.com/Jackardios/css-to-tailwindcss/issues/7. I am closing this in favour of that issue.

**Closed by ritz078** 2024-02-17 10:12 UTC
